@Mentorly.Api_HostAddress = https://localhost:7263


GET {{Mentorly.Api_HostAddress}}/api/courses

###

POST {{Mentorly.Api_HostAddress}}/api/courses
Content-Type: application/json

{
  //CreateCourseDto
}

###

GET {{Mentorly.Api_HostAddress}}/api/courses/{id}

###
